version: '3'
services:
  client:
    restart: always
    build:
      context: ./
      dockerfile: ./docker/client/Dockerfile
    volumes:
      - './:/usr/src/app'
      - /usr/src/app/node_modules/
    ports:
      - 8080:8080
    networks:
      - server
networks:
  server:
    external:
      name: server_server
