version: '3'
services:
  web:
    restart: always
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - './:/usr/src/app'
      - /usr/src/app/node_modules/
    ports:
      - 3001:3000
      - 9229:9229
    links:
      - mongo
    command:
      - yarn
      - debug
  mongo:
    image: mongo
    ports:
      - 27017:27017
