version: '3'
services:
  server:
    restart: always
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    networks:
      - server
    volumes:
      - './:/usr/src/app'
      - /usr/src/app/node_modules/
    ports:
      - 3000:3000
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - server
networks:
  server:
